# Generated by Django 3.2.9 on 2021-12-12 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workSchedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='date',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='dateFrom',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data urlopu od'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='dateTo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data urlopu do'),
        ),
    ]
