# Generated by Django 3.2 on 2021-12-19 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workSchedule', '0002_auto_20211212_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='dateTo',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='timefrom',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Pracuje od godziny'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='timeto',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Pracuje do godziny'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='dateFrom',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Pracuje od dnia'),
        ),
    ]
