# Generated by Django 3.2 on 2021-12-19 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workSchedule', '0003_auto_20211219_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='timefrom',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Pracuje od godziny'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='timeto',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Pracuje do godziny'),
        ),
    ]
