# Generated by Django 3.2 on 2021-12-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workSchedule', '0005_workschedule_datecheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workschedule',
            old_name='timefrom',
            new_name='timeFrom',
        ),
        migrations.RenameField(
            model_name='workschedule',
            old_name='timeto',
            new_name='timeTo',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='dateCheck',
        ),
    ]
