# Generated by Django 3.2.9 on 2021-12-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltyProgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loylalityprogram',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakupu'),
        ),
    ]
