# Generated by Django 3.2.9 on 2021-12-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltyProgram', '0002_alter_loylalityprogram_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loylalityprogram',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Tytuł'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loylalityprogram',
            name='info',
            field=models.TextField(verbose_name='Szczegółowy opis ngarody'),
        ),
        migrations.AlterField(
            model_name='loylalityprogram',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Cena punktowa'),
        ),
    ]
