# Generated by Django 3.2 on 2021-12-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltyProgram', '0003_auto_20211212_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='info',
            field=models.TextField(default='', verbose_name='Historia punktów dodanych przez moderatorów/adminów'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loylalityprogram',
            name='info',
            field=models.TextField(verbose_name='Szczegółowy opis nagrody'),
        ),
    ]
