# Generated by Django 3.2 on 2021-12-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltyProgram', '0005_alter_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loylalityprogram',
            name='spraw',
            field=models.BooleanField(default=0),
        ),
    ]
