# Generated by Django 3.2 on 2021-12-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltyProgram', '0006_loylalityprogram_spraw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loylalityprogram',
            name='spraw',
        ),
    ]
