# Generated by Django 3.2 on 2021-12-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyaltyProgram', '0007_remove_loylalityprogram_spraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Historia punktów dodanych przez moderatorów/adminów'),
        ),
    ]
