# Generated by Django 3.2.9 on 2021-12-07 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0002_auto_20211207_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data wakacji'),
        ),
    ]
