# Generated by Django 3.2.10 on 2021-12-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0003_alter_vacation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Zakceptowany'),
        ),
    ]
