# Generated by Django 3.2.9 on 2021-12-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0003_alter_vacation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Zakceptowany'),
        ),
    ]
