# Generated by Django 3.2.10 on 2021-12-12 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0004_alter_vacation_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='date2',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Koniec wakacji'),
        ),
    ]
