# Generated by Django 3.2.9 on 2021-12-12 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0004_auto_20211212_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='date',
        ),
        migrations.AddField(
            model_name='vacation',
            name='dateFrom',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data wakacji od'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='dateTo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data wakacji do'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Wiadomość dla moderatora'),
        ),
    ]
