# Generated by Django 3.2.10 on 2021-12-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0005_vacation_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='accepted',
        ),
    ]
