# Generated by Django 3.2 on 2021-12-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0005_auto_20211212_2200'),
        ('vacation', '0007_vacation_accepted'),
    ]

    operations = [
    ]
