# Generated by Django 3.2 on 2021-12-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0008_merge_0005_auto_20211212_2200_0007_vacation_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='date2',
        ),
    ]
